# Generated by Django 3.0.8 on 2020-08-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_cartproductlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email address')),
                ('subject', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subject')),
                ('query', models.TextField(verbose_name='Query')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date_time'],
            },
        ),
        migrations.AddField(
            model_name='cartproductlist',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
