# Generated by Django 3.0.8 on 2020-08-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200825_2119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ['date_time'], 'verbose_name_plural': 'Contact Us'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-order_date_time',), 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name_plural': 'Reviews'},
        ),
        migrations.AddField(
            model_name='contactus',
            name='seen',
            field=models.CharField(choices=[('0', 'Unseen'), ('1', 'Seen')], default='0', max_length=1),
        ),
    ]
