# Generated by Django 3.0.8 on 2020-09-06 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200905_2229'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartProductList',
        ),
    ]
