# Generated by Django 3.0.8 on 2020-09-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200907_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='zoom',
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0.0, verbose_name='Discount (%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Price'),
        ),
    ]
