# Generated by Django 3.0.8 on 2020-09-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20200908_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200, verbose_name='Tag line')),
                ('info', models.TextField(verbose_name='Information')),
                ('image', models.ImageField(upload_to='ad_banner/', verbose_name='Image')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='status_message',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
