# Generated by Django 3.0.8 on 2020-09-08 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20200908_2126'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdBanner',
        ),
    ]
