# Generated by Django 3.1.1 on 2020-09-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_delete_adbanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Order received'), ('2', 'Packed'), ('3', 'Shipped'), ('4', 'Delivered'), ('5', 'Canceled'), ('6', 'Requested for return'), ('7', 'Refunded')], default='1', max_length=1),
        ),
    ]
